-- PleaseStayHere / Supabase schema
create table if not exists public.sources (
  id text primary key,
  type text not null,
  name text,
  url text not null,
  country text,
  city text,
  last_collected_at timestamptz
);

create table if not exists public.raw_posts (
  id bigint generated by default as identity primary key,
  source_id text not null references public.sources(id) on delete cascade,
  source_post_key text not null,
  source_url text,
  author text,
  text text not null,
  images_json jsonb not null default '[]'::jsonb,
  published_label text,
  collected_at timestamptz not null default now(),
  raw_json jsonb,
  unique(source_id, source_post_key)
);

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  raw_post_id bigint not null unique references public.raw_posts(id) on delete cascade,
  dedupe_key text,
  country text,
  city text,
  area text,
  property_type text,
  bedrooms integer,
  bathrooms integer,
  price numeric,
  currency text,
  price_period text,
  available_from text,
  title text,
  description text,
  contact_phone text,
  source_url text,
  images_json jsonb not null default '[]'::jsonb,
  language text,
  is_agent boolean,
  confidence numeric not null default 0,
  created_at timestamptz not null default now(),
  content_fingerprint text,
  duplicate_of_listing_id bigint references public.listings(id) on delete set null,
  duplicate_score numeric,
  duplicate_reason text
);

create index if not exists idx_raw_collected on public.raw_posts(collected_at desc);
create index if not exists idx_listings_location on public.listings(country,city,area);
create index if not exists idx_listings_price on public.listings(currency,price,price_period);
create index if not exists idx_listings_dedupe on public.listings(dedupe_key);
create index if not exists idx_listings_duplicate_of on public.listings(duplicate_of_listing_id);

alter table public.sources enable row level security;
alter table public.raw_posts enable row level security;
alter table public.listings enable row level security;

revoke all on table public.sources from anon, authenticated;
revoke all on table public.raw_posts from anon, authenticated;
revoke all on table public.listings from anon, authenticated;

grant all on table public.sources to service_role;
grant all on table public.raw_posts to service_role;
grant all on table public.listings to service_role;
grant usage, select on all sequences in schema public to service_role;
